baseURL = "https://cultivateoakland.org/"
languageCode = "en-us"
title = "Cultivate"
theme = "hugo-initio"
publishDir = "docs"

[params]
    sitename = "Cultivate"
    logo = "images/logo.png"
    footer_logo = "images/footer_logo.jpg"
    bg_image = "images/cultivate_bg1.jpg"
    head_message_light = "Help us develop"
    head_message_bold = "kingdom workers."
    stories_message_light = "Stories of"
    stories_message_bold = "kingdom workers."
    Mdescription = ""
    email = "dc@cultivateoakland.org"
    phone = ""
    address = "PO Box 210997, Auburn Hills MI 48321"
    year = 2019
    background = ""
    favicon = "images/favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = false
    showRecentWorks = true
    showDownload = false
    showClients = false
    showQuote = false
    showAbout = true
    Paginate = 10

[[menu.main]]
	name = "about"
	url = "/about"
	identifier = "about"
	weight = 3
[[menu.main]]
	name = "vision"
	url = "../about/index.html#subheader"
	parent = "about"
	weight = 1
[[menu.main]]
	name = "overview"
	url = "../about/index.html#overview"
	parent = "about"
	weight = 5
[[menu.main]]
	name = "team"
	url = "../about/index.html#team"
	parent = "about"
	weight = 10
[[menu.main]]
	name = "history"
	url = "../about/index.html#history"
	parent = "about"
	weight = 15
[[menu.main]]
	name = "oversight"
	url = "../about/index.html#oversight"
	parent = "about"
	weight = 20
[[menu.main]]
	name = "Students"
	url = "/students"
	weight = 6
[[menu.main]]
	name = "Strategy"
	url = "/strategy"
	weight = 5
[[menu.main]]
	name = "Stories"
	url = "/stories"
	weight = 7
[[menu.main]]
	name = "Partners"
	url = "/#partners"
	weight = 10
[[menu.main]]
	name = "Donate"
	url = "#"
	identifier = "donate"
	weight = 4
[[menu.main]]
	name = "General Fund"
	url = "https://donorbox.org/cultivate"
	parent = "donate"
	weight = "10"
[[menu.main]]
	name = "Kingdom Worker Fund"
	url = "/donate/kwdf"
	parent = "donate"
	weight = 20

	
[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    # property = "123456789012345678901234"
    # custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:info@cultivateoakland.org"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
    
  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = ""
    subtitle = ""

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close"
      
# About section
  [params.about]
    enable = true
    title = "Our story"
    subtitle = ""
    endpoint = "Want to be <br>part of the story?"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "2012-2013"
      title = "Our Beginnings"
      description = "In 2013, Cam Underdown left his work at Kensington Church in north Oakland County, Michigan to embark on a journey of church planting at Oakland University. In prayer, God gave Cam three specifics to start: gather and strengthen believers, serve existing campus organizations, and not recruit team members, but instead let them come to him. A dozen people joined the initial team without Cam ever recruiting them, instead hearing about the endeavor through dreams, connections, and friends."

    [[params.about.events]]
      img = "2.jpg"
      date = "2014-2015"
      title = "Becoming Cultivate"
      description = "After two years of starting small groups, teaching classes, and strategizing about how to share the love of Jesus with the students of Oakland, it was clear that a traditional church plant was not the best means of developing kingdom workers at Oakland. In June 2015, the initiative was named Cultivate, and a process was put in place to begin developing kingdom workers in Christlike character at Oakland University that included mentoring, listening prayer, and leadership development."

    [[params.about.events]]
      img = "3.jpg"
      date = "2015-2017"
      title = "Cultivating the Campus"
      description = "In 2015-2016, leaders of various campus ministries and organizations joined the Cultivate process. Cultivate was able to assist in developing Christlike character in leaders of SpringHill Camps, Fellowship of Christian Athletes, Freedom Fighters 6.12 (an anti-trafficking organization), YoungLife, Intervarsity Christian Fellowship, Collective at Woodside, and 1829 at Kensington. Cultivate also assisted in the establishment of International Oasis, a nonprofit organization that provides support for international students in order to inspire and equip them to meet the needs of the global poor."

    [[params.about.events]]
      img = "4.jpg"
      date = "2017"
      title = "Beyond the Campus"
      description = "As the kingdom workers that Cultivate has helped to develop move beyond the campus, Cultivate continues to branch out as well. Cultivate continues to work to lend support to the kingdom workers who we have helped to develop in their business and ministry endeavors, and Cultivate offers its services to groups beyond the campus. For example, in 2017 Cultivate has assisted in the establishment and development of SLAM, a movement based around local artists to fight and end prejudice in metro Detroit."

      
